quacs/quacs

.github/workflows/gh-pages-deploy.yml, .github/workflows/lint.yml, src/App.vue, src/assets/styles/colors.css, src/assets/styles/global.css, src/assets/styles/main.css, src/assets/styles/themes/colorful.css, src/assets/styles/themes/dark.css, src/assets/styles/themes/yacs.css, src/components/Calendar.vue, src/components/CourseCard.vue, src/components/CourseSetEdit.vue, src/components/PresetEdit.vue, src/components/Settings.vue, src/components/scrapeTranscript.js, src/components/sections/Sections.vue, src/main.ts, src/store/index.ts, src/store/modules/schedule.ts, src/views/Prerequisites.vue, src/views/Schedule.vue
=> Add ability to switch amoung multiple course sets

src/components/CourseCard.vue, src/searchUtilities.ts, src/typings.ts
Demo of card UI
Searching also supported
=> course: add attribute support in display + search, resolves #26

src/assets/styles/colors.css, src/assets/styles/themes/dark.css, src/components/CourseCard.vue, src/components/sections/Sections.vue
=> Change 'Full Course' background to red to stand out from 'Full Sections'

package.json, src/store/index.ts, yarn.lock
=> Bump vuex-persistedstate from 3.0.1 to 3.1.0 

public/index.html
=> index: add og:image meta-tag for embed icon

.github/workflows/gh-pages-deploy.yml, .github/workflows/lighthouse.yml, .github/workflows/lint.yml, src/quacs-rs/Cargo.toml
- Updates CI to switch from fork to rust wasm, this brings the CI build times down close to 5 minutes
=> Fix building quacs with prebuilt wasm-pack

.github/workflows/gh-pages-deploy.yml, .github/workflows/lighthouse.yml
=> Fix CI (install dependencies for node-canvas)

.github/workflows/scrape.yml, scrapers/prerequisites_graph/main.py
This should (hopefully) fix the scraper GitHub action
=> scrapers: prereq graph: fix wrong paths

scrapers/sis_scraper/main.py
Fixes #273
This change modifies sis-scraper to ignore semesters that were previously completed.
In its current design, the html will still be pulled down and parsed; however, all other steps will be skipped once it has been determined that the semester has ended.
=> sis-scraper: skip semesters that already ended

scrapers/prerequisites_graph/main.py, scrapers/prerequisites_scraper/main.py
The prereq* scrapers didn't handle skipping semesters -- this change fixes them up so the quacs-data commits should start working.
Note: linter issues are pre-existing
=> Small scraper fix

.github/workflows/scrape.yml, .gitignore, scrapers/transfer_scraper/main.py
I tried to add types but it is really hard when I am using bs4 and it does not have types
=> Add a scraper for the RPI Transfer Course Guide

site/src/views/Schedule.vue
Resolves #391.
I don't know courses with multiple sections that all don't have any times so I was unable to check that only one of those sections is added, but the code seems right to me.
=> Add courses with no timeslots to CRN list

.github/workflows/scrape.yml, .gitignore, scrapers/transfer_scraper/main.py
Given we have no immediate plans to add this data to the website front end, I thought I would add a human readable form to this repo. This information is something that lots of departments are interested in, but not everyone can read a json file off the top of their head. This creates a folder of csv files that can be shared with anyone with a basic csv parser.
=> Add csv output to transfer data scraper

scrapers/sis_scraper/main.py
From time to time, our "Scrape courses and prereqs" action will fail as a result of not being able to login to SIS which means data gets delayed.
This change introduces a retry mechanism to help avoid these random failures from breaking the whole action.
=> sis-scraper: retry login if we fail to scrape

site/scripts/gh-pages-deploy.sh
Fixes https://github.com/quacs/quacs/runs/2179285264
=> gh-pages-deploy: don't exit with status 1 if no changes are available

site/src/App.vue
=> search: encode search data using encodeURIComponent, fixes #337

site/src/views/Schedule.vue
Per issue description: change schedule.ics to {course_set_name}.ics
This saves the course set name as lower snake case per request.
=> schedule: change schedule.ics to {course_set_name}.ics, resolves #319

.github/workflows/scrape.yml
We're already in the data directory by this point
=> scrape: correct path for meta.json

site/package.json, site/src/components/Calendar.vue, site/src/components/SemesterBars.vue, site/src/components/scrapeTranscript.ts, site/src/store/modules/schedule.ts, site/yarn.lock
Replaces https://github.com/quacs/quacs/pull/480
=> Prettier 2.3.0

scrapers/sis_scraper/main.py
Addresses GH action failures:
1. https://github.com/quacs/quacs/runs/2605604367
2. https://github.com/quacs/quacs/runs/2605310604
See 'Fall 2020 ECSE-6900 Seminar in ECSE Section 01' for what triggered this change.
=> sis-scraper: handle new credit syntax in SIS

.github/workflows/lint.yml
=> ci: fix wasm-pack 10.0 breakages

site/package.json, site/src/App.vue, site/src/registerServiceWorker.ts, site/yarn.lock
Addresses build issues from #612
=> Typescript 4.4.2

scrapers/sis_scraper/conflict_logic.py, scrapers/sis_scraper/main.py, scrapers/sis_scraper/util.py
1. Fix schools.json non-determinism with the "Uncategorized category" by sorting the results (minor: only affected git diffs). 
2. Fix "Readings in X" courses causing type-errors.
=> More fixes for sis-scraper

site/src/components/sections/SectionInfo.vue
=> Fix spacing in section info (issue #713)

.github/workflows/scrape.yml, scrapers/sis_scraper/main.py, scrapers/sis_scraper/util.py, site/scripts/short_sem_to_long_sem.py, site/src/utilities.ts, site/vue.config.js
https://info.rpi.edu/undergraduate-education/enrichment-term
=> Winter 2021 "Enrichment term" support

site/src/App.vue
=> app: switch to christmas logo

.gitignore, scrapers/requirements.txt, scrapers/sis_scraper/main.py
I need to test this but I forgot how to do it correctly :)
=> Fix classes that have a syllabus on sis

.github/workflows/scrape.yml
also change `cp` to `rsync` and fix indentation
=> Copy csci_topics data so it actually works

scrapers/sis_scraper/main.py
How did I screw this up, I don't know.
Note that for some reason using `splitlines()` instead of `split("\n")` broke everything.
=> Fix SIS scraper

scrapers/sis_scraper/main.py
=> Maybe fix SIS catalog scraper for real this time

scrapers/sis_scraper/main.py
due to registration date index out of bounds
=> Fix scraper crash on empty semesters

scrapers/prerequisites_graph/main.py
=> Fix course names in prereq graph by using catalog names when possible

.github/workflows/scrape.yml, scrapers/abc_eats/get_data.py
The v3 version of these actions are deprecated: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions
=> Switch to artifact@v4 action

.gitignore, README.md
Had some trouble with mac installation. Added a couple links to help and another note that wasm-opt led to the site not building at all.
=> Improve Readme Instructions
