quacs/quacs

src/components/sections/SectionInfo.vue
src/components/sections/Sections.vue

The 'Seats' section would read as:
Seats:
There are min/max seats available available...
This commit removes the duplicate available

Fix bug where available was showing up twice in a row

---

.github/workflows/lint.yml
src/store/index.ts
src/views/Department.vue
src/views/Prerequisites.vue
vue.config.js
yarn.lock

This change fixes various type errors from the previous upgrade (see #75,76)
by either correcting where obvious and easy, or temporarily whitelisting
the new violations.
This change also enables the "lint" action for PRs, blocking them
from being merge-able to ensure stability on master.

lint: fix errors from eslint upgrade

---

src/components/Calendar.vue
src/components/sections/Sections.vue
src/utilities.ts

The fall 2020 semester brought a depressing addition of a class,
BIOL-4720: Molecular Biology Lab, which has a section that
meets on a Saturday.
This change adds support for QuACS being able to support
courses with Saturday meeting times in both the section view
and calendar / schedule overview.
Per request, the section cards will only display weekend days
iff. a course has a timeslot on a weekend.

schedule: add support for weekend (Saturday) courses

---

.github/workflows/lighthouse.yml

Brings back the green check-mark + we can visualize performance hits again

build: patch lighthouse performance action to use working wasm-pack

---

.github/dependabot.yml

It didn't like the ignored_updates section anymore, so I just removed it as we've successfully handled eslint updates in the past.

dependabot.yml hotfix

---

src/components/Calendar.vue
src/components/sections/Sections.vue

Fall 2020 brought us the suprise of Saturday classes, Spring 2021 brings us the suprise of Sunday classes ('U').
This commit leverages the existing infrastructure of only including saturday/sunday on the course times if the class has a weekend timeslot (unlikely) to reduce clutter.

schedule: add front-end support for sunday classes

---

.github/workflows/gh-pages-deploy.yml
.github/workflows/lighthouse.yml
.github/workflows/lint.yml

ci: bump setup-node to latest version to avoid major breakages

---

site/package.json
site/src/views/Schedule.vue
site/yarn.lock

This PR fixes 2 issues
1. The ics export would sometimes cause issue in google calendar and default timeblocks to an hour
2. if you are not in rpi time, the export button would assume you were causing timezone issues

Fix issue with ics export not working in google calendar as well as fix timezone issues

---

site/src/views/Schedule.vue

yyyy-MM-dd is not an officially supported format for the Date constructor. On WebKit-based browsers (Epiphany, Safari),
this results in "Invalid Date" being returned -- which causes an infinite loop in exportIcs()
See: https://stackoverflow.com/questions/4310953/invalid-date-in-safari

calendar: fix ICS generation failing on WebKit-based browsers

---

site/scripts/build_entry.sh

If umami crashes, then instead of downloading umami.js it will download an nginx error. This checks for that and exits the build process.

Add check to make sure umami.js downloads correctly

---

scrapers/prerequisites_graph/main.py

See the prereq_graph.json history for context https://github.com/quacs/quacs-data/commits/master/prereq_graph.json
This change introduces a sorted order for ("and","or") prereqs. By default, python's sets are unordered, making their ordering non-deterministic. Instead of building a list from the set using list(), call sorted() to ensure a deterministic order

prereq_graph: fix non-determinism in json generation

---

.github/workflows/gh-pages-deploy.yml
.github/workflows/lighthouse.yml
.github/workflows/lint.yml

The vue-visjs package no longer depends on node-canvas, so the CI doesn't need to install dependencies for it.
https://github.com/sjmallon/vue-visjs/issues/7

CI: Remove no-longer-used node-canvas dependencies

---

.github/workflows/scrape.yml

While this data is nice to have and failures should be fixed ASAP, a minor network issue should not stop a quacs-data update from going through.

scrape: make faculty, hass, and transfer failures non-fatal

---

.github/workflows/scrape.yml

rsync will raise this in the event that a partial transfer occurs - the || true will ignore this.

scrape: ensure rsync doesn't raise exit status 23

---

.github/workflows/scrape.yml

This will allow us to make a hard_coded folder inside any semester folder and then it will take the hard coded content from there and merge it into the catalog.json file
Here is an example of some hard coded data https://github.com/quacs/quacs-data/commit/224ebf5e2b9fc388a080ca4883990540053c6f5b

Merge in hard coded catalog data before pushing to quacs-data

---

.github/workflows/scrape.yml
scrapers/hass_pathways_scraper/main.py

Example runtime: https://github.com/quacs/quacs/runs/2188485099?check_suite_focus=true
The hass scraper has run into an issue where it will proceed to run indefinitely (until the 6 hour timeout hits) during some of its runs. It has only been reproducable on Github Actions.
This change enforces a 10 minute timeout to ensure we aren't hoarding resources while the root cause is determined.
Debug prints have been added to the scraper to help determine the root cause.

scrape: enforce 1 minute timeout on HASS pathway scraper

---

site/src/quacs-rs/Cargo.toml

See: https://github.com/quacs/quacs/runs/2215453921
Credit to: https://github.com/rustwasm/wasm-bindgen/issues/2508

quacs-rs: force syn=1.0.65 to address site build failures

---

site/src/quacs-rs/Cargo.toml

Reverts quacs/quacs#425
No longer needed since we have dbf3cff5e161d9de5a63cf2d12aef8a3aef7184e

Revert "quacs-rs: force syn=1.0.65 to address site build failures"

---

site/package.json
site/src/views/Schedule.vue

Resolves #269 
- Removes moment.js dependency, no longer needed.
- Manually update the DTSTART/DTEND fields to pin the timezone to America\New_York instead of UTC. This addresses issues with daylight savings time shifting the times. Calendar apps should be able to do the necessary conversions.

schedule: fix ICS exporting, resolves #269

---

scrapers/catalog_scraper/main.py
scrapers/sis_scraper/main.py
site/src/components/CourseCard.vue
site/src/components/sections/SectionInfo.vue
site/src/components/sections/Sections.vue
site/src/typings.ts

This resolves #271.
From commmit 96e9760:
"This commit enables support for scraping and displaying course closed indicators (defined as 'NR' - Not available for registration  or 'C' - closed on the sis view).
For the QuACS UI, a course is defined as closed when the following conditions are met:
1. All sections have 'closed':true set.
2. The course is not full.
This avoids redundant labeling since for all intents-and-purposes a full course is a closed course.
For sections, the logic is similar except the individual section attribute and size is checked."

Support for closed indicators

---

site/src/components/sections/Sections.vue

The closed indicator should be reserved for non-obvious closures, such as cross list slot exhaustion.

sections: display full section indicator instead of closed, if applicable

---

site/scripts/lint.sh
site/src/quacs-rs/Cargo.lock
site/src/quacs-rs/Cargo.toml
site/src/quacs-rs/src/lib.rs
site/src/quacs-rs/src/test_context.rs

Fixes part of https://github.com/quacs/quacs/issues/28.
The tests are added to the CI and it tests both native binaries and WASM-compiled tests in node.js. There is a test for the CURR_TIMES bug but it's marked with `#[should_panic]` until that's fixed.

Add quacs_rs tests

---

.github/workflows/scrape.yml

We don't rebuild the site anymore when nothing changes thanks to partial rebuilds, therefore commits that only change meta.json seek to just gradually increase the data repo's size.

scrape: don't commit if only meta.json changed

---

.github/workflows/scrape.yml

Github actions will continue to run following steps if we exited prematurely with success. This works around that by merging the deployment step into the commit step.

scrape: don't run deploy hook if we didn't commit

---

.github/workflows/gh-pages-deploy.yml

This change introduces a lock in the gh-pages-deploy action. This prevents site rebuilds from intefering scraping and vice-versa.

ci: fix race condition in deployment

---

scrapers/requirements.txt

Updates to the python dependencies in the scrapers will now be managed by dependabot. This helps ensure a more deterministic CI process.
A notable short coming is we have no good way to do correctness testing of scraper changes until the next scraping run; however, if we start getting sudden CI failures we can look to see if dependabot made any changes.

scrapers: pin versions in requirements.txt

---

site/src/quacs-rs/src/test_context.rs

The ordering of a map key iteration is undefined and therefore
this test fails if the ordering is changed.
This fixes test failures in https://github.com/quacs/quacs/pull/527

quacs-rs: use deterministic iteration in test_freshman_cs()

---

site/src/views/Schedule.vue

Hovering over CRN in the schedule view gives a tooltip - "Click to copy CRN for [class name]"
Resolves issue #255.

Tooltip for crn list

---

site/src/views/Schedule.vue

When simplifying the ics logic as part of https://github.com/quacs/quacs/commit/560dcf06f2522b917e86e0f897297b55c74f52d7,
getSeconds() was used instead of getMinutes().

schedule: fix regression in schedule generation, resolves #613

---

.github/workflows/scrape.yml

The Fall 2021 schools are now officially available which is causing this
step to fail.
Resolves following CI failures:
1. https://github.com/quacs/quacs/runs/3623016096
2. https://github.com/quacs/quacs/runs/3622336466
3. https://github.com/quacs/quacs/runs/3621755424
4. https://github.com/quacs/quacs/runs/3621242458

scrapers: remove hack for fall 2021

---

.github/workflows/lint.yml
.github/workflows/scrape.yml
scrapers/datadog/send_metrics.py
scrapers/requirements.txt
scrapers/rmp_scraper/main.py

This adds python black to the ci because I realized we did not have a python linter
I also disable the datadog stuff for now. We can maybe at some point work on updating that code to fit within the datadog limits or use it to write our own metrics to the quacs-data repo

Add python black to CI and disable datadog

---

scrapers/sis_scraper/main.py
scrapers/sis_scraper/util.py

Python's .title() makes "MASTER'S PROJECT" turn into "Master'S Project" which is suboptimal.
Additionally, this supports basic Roman Numerals (I,II,III) to make them look nicer.

sis-scraper: fix text normalization

---

scrapers/sis_scraper/main.py
site/src/components/CourseCard.vue
site/src/components/sections/SectionInfo.vue
site/src/components/sections/Sections.vue
site/src/typings.ts

This change scrapes the `xl_rem` (number of total cross-listed seats
remaining for each course) and modifies the frontend to support
handling full cross-listed courses.
Cross listed courses have a total amount of seats available across
all the sections. Once this is exhausted, you cannot register even
if the section has seats left. This gives people (including myself
at times) a lot of false hope that they can actually register for a course.
A few months back, we started scraping the 'closed' attributes on SIS.
However, this no longer works with the new scraper, so we have to
mimic this functionality.

schedule: remove the 'closed' attribute, re-introduce XL logic

---

scrapers/requirements.txt

No longer used. I meant to get rid of this earlier
but forgot. Dependabot triggered a reminder when it tried
to update the dependency.
https://github.com/quacs/quacs/pull/717

scrapers: drop python-dotenv dependency

---

site/src/views/Schedule.vue

1. Add basic support for cross-year classes (like the Winter Enrichment term)
- Future improvement: refactor start/end to use a unix timestamp or something similar.
2. Fix an off-by-one issue  where classes that ended on the last day of the semester didn't have an event generated.
e.g. A Spring 22 class that ended on Friday May 6th wouldn't generate
an event.

schedule: misc .ics generation  improvements

---

scrapers/prerequisites_graph/main.py
site/src/components/sections/SectionInfo.vue
site/src/utilities.ts

Adds course names to info modal. I did however decide not to add it to the graph part because it just became a mess and I dont think it is really needed
One note, this screenshot does not have all the courses labeled because not all the data existed in the prerequisite graph before this pr. But now I add courses with no prerequisites to that file so that we have the names of the courses 
I also added some try catches around some umami code. It was causing me issues locally and anyway we dont want the website to break if umami is down so this solves that problem

Add course titles to prerequisites and add corequisites

---

scrapers/sis_scraper/main.py
scrapers/sis_scraper/util.py

This resolves an issue noticed where fall 2021 stopped
being scraped because we're now in December and Winter Enrichment starts in December.
This also would've been observed in spring -> arch transitions as the spring ends
in May and Arch starts in May.
To address this, if our starting month is in RPI_SEMESTER_MONTH_OFFSETS,
just rollback to the previous semester.

sis-scraper: adjust behavior in get_semesters_to_scrape

---

scrapers/sis_scraper/util.py

This is an oversight from the previous commit which fixed
back-to-back semester scraping. If we are in January,
the previous code would 'roll back' a month to 0
and then proceed in an infinite loop going negative
until interrupted or killed by the 6 hour timeout
on Github Actions.
To fix this, simply set the starting month to the
maximum in the offsets set if we hit 0.

sis-scraper: avoid infinite loop if run in January

---

scrapers/sis_scraper/util.py

minor fixes. i verified this by just faking the date object to be in january and watched it decrement appropriately

sis-scraper: ensure year is decremented during wrap-around

---

scrapers/sis_scraper/conflict_logic.py
scrapers/sis_scraper/sis_scraper_test.py

Fix 1:
Ben pointed something out to me in the code that ended up
being a non-issue. However, upon closer inspection, I found
we were needlessly building a set when we could just count
the number of redundant pairs and break early to avoid counting
duplicates
Fix 2:
I've been noticing some non-determinism in the bitpacks for the semesters.
Its very minor in fall2021 and spring2022. However, in Winter Enrichment 2021
its been very common. I believe I've isolated it to the unique_ranges set.
It's being iterated through and since sets have an undefined ordering
this could be the source of the problem. This is a regression caused
by 79d91d75c023b08599298a02f549346ff63af81c
Fix 3:
Minor improvement to the sis_scraper_test to report back information
about failures instead of simply printing …

conflict_logic: minor improvements and optimizations

---

.github/workflows/scrape.yml
scrapers/catalog_scraper/main.py
scrapers/sis_scraper/main.py

This rewrites the entire catalog to use the catalog API
It is much faster and does not cause the catalog to crash therefore we can add it back into the scraper. (which I still need to do and why this PR is WIP)
I also made it so that it generates the catalog for the next year using the current catalog. This will help when we transition between semesters but the catalog has not gotten a new version which has happened before.

Rewrite catalog scraper to work with API

---

site/src/assets/styles/colors.css
site/src/assets/styles/global.css

just makes it so you can change the color of the borders on the cards with themes more easily. 
It was hard coded before, it looked like maybe it just came from some bootstrap thing maybe ? I couldn't find where it was coming from in any of the quacs files atleast so I figured it wouldn't be an issue to just override it. 
It keeps the same default so everything will look the same unless a theme overrides it.
added because the default borders didn't look great with the theme I'm working on.
It will change the color of the tables in the course cards too. I figure since they're already the same just keep it the same ? But wouldn't be too hard to pop that out to its own variable if it seems like it's an issue.

themeable card borders

---

site/src/assets/styles/colors.css
site/src/components/Calendar.vue

works on macos with firefox, chrome, and safari. I'd assume it works fine on other stuff too or just doesn't change it. 
Mobile seems to just ignore it, atleast on iOS with those same browsers.
Also added CSS variables to colors.css so that the scroll bars can be customized with themes, by default it just links back to the background and border colors so it can adjust on its own. 
I suppose it fixes #32 ? Not entirely sure if that's what you all had in mind for it or not.
also turned off the 'temp fix for borders not showing up' on the calendar events, not really sure what that was supposed to be fixing but I think it looks better without it ? especially since now the left border can go up all the way instead of having a weird triangle cut out of it at the top.

scroll bars have color now

---

.github/workflows/test.yml
site/tests/e2e/specs/department.js
site/tests/e2e/support/index.js

Edited the data to reflect what is currently displayed on https://quacs.com/summer2021, and double-checked that it is accurate to SIS. Cypress tests work now.

Fix cypress (for now)

---

scrapers/catalog_scraper/main.py

Finally! Before, the code would re-encode as UTF-8 which sometimes caused Â to appear. The catalog API seems to return either UTF-8 or ASCII encoded content arbitrarily, so this change makes the scraper handle any encoding appropriately.

Fix Â double-encoding issues

---

site/src/components/CourseCard.vue

RCOS currently shows as "1 credit" despite the fact that it can be taken for 1-4 credits. This is because the old logic just picked the first section and took the credit information from that. This change accounts for sections having different credit numbers by checking all of them and finding the minimum and the maximum credits this way.
The motivation for this is that I was going to take RCOS at some point last year but I decided against it because I thought it was only 1 credit, even though it wasn't, due to this confusion. I also accounted for this in the Quatalog because it kept annoying me.
Currently, QuACS shows RCOS like this:
This change makes it show RCOS like this:

Show courses whose credit counts vary by section properly

---

.github/workflows/codeql-analysis.yml
.github/workflows/gh-pages-deploy.yml
.github/workflows/lighthouse.yml
.github/workflows/lint.yml
.github/workflows/scrape.yml
.github/workflows/test.yml

fixes various deprecation warnings
See: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

ci: bump actions to latest major versions

---

.github/workflows/gh-pages-deploy.yml
.github/workflows/lighthouse.yml
.github/workflows/lint.yml
.github/workflows/scrape.yml
.github/workflows/test.yml
site/scripts/build_single.sh

1. bumped Node.JS to 18.x LTS branch (from 16.x LTS) -- 16.x support is ending in 5 months
2. bumped python from 3.10 to 3.11
3. bumped lhci/cli so lighthouse works under new node
4. disabled hass pathway scraper since its broken (outputs empty JSON)
5. made commit-changes wait on scrape-transfer to complete (failure is okay) to ensure transfer scraping will make it into commit

Moar ci updates

---

site/src/App.vue

fixes #990 Made the semester dropdown as scrollable menu with a max height of 25% of viewport height and min height of 5 rem.

scrollable semester dropdown for issue 990

---

scrapers/catalog_scraper/main.py

API was returning 403 forbidden for anything larger

scrapers: drop CHUNK_SIZE to 100 to fix catalog scraper

---

scrapers/csci_topics_scraper/main.py

Some aiohttp update broke SSL validation so now the Goldschmidt scraper is broken. Here is a fix.

Disable SSL validation in CSCI topics scraper

---

.github/workflows/scrape.yml
scrapers/catalog_scraper/main.py
scrapers/csci_topics_scraper/main.py
scrapers/sis_scraper/main.py

Scrapes course descriptions from https://sis.rpi.edu/rss/bwckctlg.p_display_courses?term_in=202309&one_subj=CSCI&sel_crse_strt=0000&sel_crse_end=9999&sel_subj=&sel_levl=&sel_schd=&sel_coll=&sel_divs=&sel_dept=&sel_attr= .
The original catalog scraper is left alone, and this SIS catalog data is used as a fallback when the Acalog catalog has no data for a course. The motivation for this is that RPI is really dragging its feet at releasing the new catalog, and there are a couple new courses with SIS descriptions but without catalog descriptions, [BIOL-1016](https://sis.rpi.edu/rss/bwckctlg.p_disp_course_detail?cat_term_in=202309&subj_code_in=BIOL&crse_numb_in=1016) and [CHEM-4750](https://sis.rpi.edu/rss/bwckctlg.p_disp_course_detail?cat_term_in=202309&subj_code_in=CHEM&crse_numb_in=4750).

Add SIS catalog scraper

---

scrapers/csci_topics_scraper/main.py

HTTP response says that the file uses UTF-8 but it actually uses Windows-1252, so this forces the scraper to use the correct encoding.

Fix decoding crash in CS topics scraper

---

.github/workflows/scrape.yml

The `https://www.cs.rpi.edu/~goldsd/docs/` page, which used to be an open access directory listing, is now 403. This breaks the scraper. This PR disables it.

Disable CSCI topics scraper

---

site/src/store/modules/schedule.ts

Before:
https://github.com/user-attachments/assets/07ec8581-f06c-4be5-87cd-ef9d7b69385b
After:
https://github.com/user-attachments/assets/b6083efa-3ff4-474b-aa53-00406425442b
Related to #767 
Deleteing a courseset should delete all the courses in the worker. The function deleted the course set first, so the other function doesnt know the courses that its suppose to be deleted. This leads to a disabled vue view and the worker showing available schedules.

Deleting a courseset should delete all the courses

---

site/src/views/Schedule.vue

MinCredit==maxCredit
With RCOS which has 1-4 credits
closes #275
note: export ics button becomes a little bigger

Add Credits Counter/Range
